apiVersion: v1
kind: Namespace
metadata:
  name: youtube
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: demo-db
  namespace: youtube
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.1-0
  postgresVersion: 16
  instances:
    - name: demo-db
      metadata:
        labels:
          name: demo-db
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
  users:
    # TODO: disable postgres user login in production
    - name: postgres
      databases:
        - postgres
    - name: demo-owner
      databases:
        - demo
        - demo_shadow
      options: "SUPERUSER LOGIN"
    - name: demo-owner-shadow
      databases:
        - demo_shadow
        - demo
      options: "SUPERUSER"
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host all all 0.0.0.0/0 md5"
